import Header from "@/components/header/Header";
import "./globals.css";
import { Bellefair, Mohave, Roboto } from "next/font/google";

const bellefair = Bellefair({
  weight: ["400"],
  variable: "--font-belle",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head lang="es" />
      <body className={`${bellefair.className} min-h-screen max-h-full`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
