import Header from "@/components/header/Header";
import "./globals.css";
import { Zen_Antique, Mohave, Roboto } from "next/font/google";

const zenAntique = Zen_Antique({
  weight: ["400"],
  variable: "--font-zen",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-roboto",
});
const mohave = Mohave({
  weight: ["300"],
  variable: "--font-mohave",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head lang="es" />
      <body className={`${zenAntique.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
